### PR TITLE
Add support for the `--experimental` option

### PR DESCRIPTION
**Pull request by seefood**

### CODE REVIEW

**Comment by n0k0m3** [comment]
Can you add an action for `experimental` flag + documentation (or some notes) about the `experimental` flag in `README`?

**Comment by seefood** [comment]
I guess so. It's time I learn Github ops :)

**Comment by seefood** [comment]
I hope this is what you meant?

**Comment by n0k0m3** [comment]
Make a separate `yml` file in `workflow` directory. GitHub Action will populate it as a separate build action rather than coupling this in current build

**Comment by n0k0m3** [comment]
Thanks for the PR

**Pull request merged**
