### PR TITLE
build_revanced: Make packages optional

### PR DESCRIPTION
**Pull request by taalojarvi**
Currently, the script builds all packages regardless of whether the user wants them or not. Make the script user configurable by sourcing the configuration from a "build.targets" file. Each user can configure which packages to build/skip depending on their use case by modifying the values stored in build.targets. 

Any value other than "true" will skip the package from being built.

This PR addresses Issue #53

### CODE REVIEW

**Comment by SubZeroPlayerEz** [comment]
It would be good to make inputs in the workflow for this.

**Comment by SubZeroPlayerEz** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by SubZeroPlayerEz** [comment]
> It would be good to make inputs in the workflows for this.

If you want, I'll take care of it.

**Comment by n0k0m3** [comment]
This looks perfect, do you mind editing `README.md` for this PR as well?

**Comment by taalojarvi** [comment]
> This looks perfect, do you mind editing `README.md` for this PR as well?

I have edited  README.md to document the function

**Pull request merged**
