### PR TITLE
bumped youtube version

### PR DESCRIPTION
**Pull request by sawankumarbundelkhandi**
* bumped youtube version to 18.15.40

### CODE REVIEW

**Comment by n0k0m3** [comment]
can you split this into 2 PR? 1 PR for removing `spoof-signature-verification` patches from inclusion and 1 PR for bumping YT version (this one)

**Comment by SoughtXp** [comment]
This is a mess. Why not do a rebase and drop the commits that revert and re-add change 10f6b2f?

In addition, use the command line to revert commit 10f6b2f.

For example: git revert 10f6b2f

**Comment by SoughtXp** [comment]
In addition, use the project’s standard for title. For example a3cc635.

**Comment by SoughtXp** [comment]
In addition, use the project’s standard for writing titles. For example a3cc635.

**Comment by SoughtXp** [comment]
This is a mess. Why not do a rebase and drop the commits that revert and re-add change 10f6b2f?

**Pull request merged**
