### PR TITLE
?

### PR DESCRIPTION
**Pull request by TemporaryUserYes**

### CODE REVIEW

**Comment by Caio99BR** [comment]
Personally I don't see too much improvement here, since this patch  will make the repo rely only on CI

**Comment by n0k0m3** [comment]
I don't think the implementation make sense, I'd prefer see 6-7 options true/false to build multiple packages in 1 action. Or we can even make multiple workflows for different build.

Using `build_choice` type `text` would make more sense but it'll reduce the convenience of `option`

I think further discussion will be needed for this

**Comment by Caio99BR** [comment]
> > Personally I don't see too much improvement here, since this patch will make the repo rely only on CI
> 
> Isn't that the purpose of the repository?

I mean, if it really was to be CI only, there is no meaning to `versions.json` etc

**Comment by taalojarvi** [comment]
Wouldn't this patchset break schedule workflow like mine?

While I definitely appreciate this implementation, I think a more elegant solution would be to merge the patches config file with build.targets so that one config file handles everything config related.

**Pull request closed without merging**
