### PR TITLE
Add disable-shorts-button and hide-cast-button patch

### PR DESCRIPTION
**Pull request by MatadorProBr**
The title says it all.

### CODE REVIEW

**Comment by n0k0m3** [comment]
By default the script already use all available patches so what's the use of this? @MatadorProBr

**Comment by MatadorProBr** [comment]
> By default the script already use all available patches so what's the use of this? @MatadorProBr

Basically the shorts patch, they changed the name so it doesn't work putting "shorts-button" instead of "disable-shorts-button"

**Comment by MatadorProBr** [comment]
> can you please provide complete list of integrations/pathes that we can use with the argument -i while building the apk.

Just check the "build_revanced.sh" file and you will see all the available integrations/patches

**Comment by n0k0m3** [comment]
Fair thanks for the PR

**Pull request merged**
