### PR TITLE
build_revanced: Add support for ReVanced Extended patcher

### PR DESCRIPTION
**Pull request by taalojarvi**
This PR adds support for the ReVanced Extended patcher.  Uses existing get_artifact_download_url macro and build.targets config file for ease of implementation and configuration.

Support can be toggled by modifying the value of `EXTENDED_SUPPORT` in `build.targets`. Documentation has also been updated to add references to ReVanced Extended list of patches and configuring the build.targets file for support.

Have a feeling that this implementation can be improved, so comments and suggestions are welcome!

Ref: https://github.com/inotia00/revanced-patches/tree/revanced-extended#-patches

Fixes: https://github.com/n0k0m3/revanced-build-template/issues/89

### CODE REVIEW

**Comment by SoughtXp** [comment]
This does not fully add support for ReVanced Extended.

**Comment by taalojarvi** [comment]
> This does not fully add support for ReVanced Extended.

Please elaborate?

**Comment by SoughtXp** [comment]
> 

Okay, good luck. I really appreciate this change.

**Comment by taalojarvi** [comment]
> Okay, good luck. I really appreciate this change.

Fixes made. Please verify

**Comment by SoughtXp** [comment]
YouTube ReVanced Extended is already on version 18.15.40.

**Comment by taalojarvi** [comment]
> YouTube ReVanced Extended is already on version 18.15.40.

Wouldn't be an issue since the user can modify versions.json to reflect the same I'm assuming?

**Comment by SoughtXp** [comment]
I think it’s better to separate the versions of YouTube and YouTube Music when EXTENDED_SUPPORT is true.

Maybe create a new file with the versions?

**Comment by SoughtXp** [comment]
For example: If EXTENDED_SUPPORT is true, assume versions_extended.json.

**Comment by taalojarvi** [comment]
> For example: If EXTENDED_SUPPORT is true, assume versions_extended.json.

That's a good idea. Waiting on repo owner input before proceeding

**Comment by n0k0m3** [comment]
> I think it’s better to separate the versions of YouTube and YouTube Music when EXTENDED_SUPPORT is true.
> 
> Maybe create a new file with the versions?

I agree with this.

Also since this repo currently supports other packages from mainline ReVanced let's add condition if EXTENDED_SUPPORT==true then not build other packages except YT/YTM

**Comment by taalojarvi** [comment]
> > I think it’s better to separate the versions of YouTube and YouTube Music when EXTENDED_SUPPORT is true.
> > Maybe create a new file with the versions?
> 
> I agree with this.
> 
> Also since this repo currently supports other packages from mainline ReVanced let's add condition if EXTENDED_SUPPORT==true then not build other packages except YT/YTM

I have implemented your comments. Please review and leave feedback / provide sign-off if everything looks okay to you.

**Pull request merged**
