### PR TITLE
feat: Use separate file for excluding patches

### PR DESCRIPTION
**Pull request by ManorSailor**
This has been thoroughly tested & no inconsistencies were found in the tests. All the tests were performed using github actions on a private template of this repository. Generated apks were also tested on android device & they worked just fine.
Despite of all this, if you find any inconsistencies, do let me know!

I haven't had the time to update readme, although, I have tried my best to include proper instructions in patches file.

Signing off,
Sars.

Edit: Squashed commits

### CODE REVIEW

**Comment by n0k0m3** [comment]
This is clean, thanks for the PR

**Comment by ManorSailor** [comment]
@n0k0m3 Btw, readme will need an update to reflect the current changes

**Comment by n0k0m3** [comment]
Best way to do this is turn your `patches.txt` to a markdown file, replace with an empty `patches.txt` + `.gitignore` entry.
This will allows update PRs when revanced team add new patches while minimizing merge/fetch from upstream conflicts

**Comment by ManorSailor** [comment]
> Best way to do this is turn your `patches.txt` to a markdown file, replace with an empty `patches.txt` + `.gitignore` entry. This will allows update PRs when revanced team add new patches while minimizing merge/fetch from upstream conflicts

Quite neat! I didn't think of that, I learned something new today. 
On a side note, script will have to be updated. Although, not updating it will not break anything for now. I will do that tomorrow morning

**Pull request merged**
